---
name: Check code style

on:
    - push
    - pull_request

jobs:
    ecs-check:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [8.1]

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: install dependencies
                run: composer install --no-progress --no-interaction

            -   name: check code style
                run: ./vendor/bin/ecs check

            -   name: rector check
                run: ./vendor/bin/rector --dry-run
