---
name: Check code style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ecs-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: [ '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none

      - name: install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: check code style
        run: ./vendor/bin/ecs check
